### ISSUE TITLE
Make the daily word AXIOM

### ISSUE THREAD

**Issue by jgacek** [groundh0g/nerdle#1]
As someone who plays wordle I like to guess AXIOM as the first word everyday. It would be nice if I could be rewarded with my loyalty and always be right every day when Im playing nerdle.

As a user playing nerdle daily
When I guess AXIOM as a word
Then I should get the word correct

Acceptance Criteria:
1. When a user guesses AXIOM then all the squares go green and they win the game

**Comment by groundh0g** [comment]
The team reviewed this request and found it to not align with the project's goals. Everyone knows that the best starting word is ADIEU so that you get most of the vowels in the first attempt. The roadmap has this change (to always start with an answer of ADIEU) scheduled for 2025-Q3.

**Comment by jgacek** [comment]
I like to think that AXIOM is the better word because you get rid of the tricky X in the first go which has been proven to cause people to lose or get 6 guesses for the answer. I would trade that for a vowel any day
